"""External-system adapters used by M1 Power Lab.

The package deliberately exposes narrow, typed interfaces.  Model output and
operator input must be turned into these types by the coordinator before an
adapter can act on them.
"""

from .hardware import (
    CaptureMemory,
    HardwareAdapter,
    HardwareCapability,
    HardwareDispatch,
    HardwareError,
    HardwareResult,
    HardwareResultStatus,
    HardwareUnavailable,
    HardwareOperation,
    InspectRegister,
    M1N1_QUALIFICATION_MESSAGE,
    M1n1HardwareAdapter,
    ReplayHardwareAdapter,
    ReplayMismatch,
    ReplayStep,
    SimulateBoot,
    TargetSnapshot,
    WaitForReplay,
)
from .runtime import (
    AppServerCodexAdapter,
    CodexRuntime,
    JobHandle,
    JobRequest,
    JobStatus,
    NoopCodexAdapter,
    RuntimeEvent,
    RuntimeErrorBase,
    RuntimeOutcomeUnknown,
    RuntimeProtocolError,
    RuntimeRequestNotSent,
    RuntimeRequestRejected,
    RuntimeUnavailable,
    SandboxMode,
    TokenUsage,
)
from .helper_protocol import (
    HELPER_PROTOCOL_VERSION,
    HelperProtocolError,
    decode_request as decode_helper_request,
    decode_request_frame as decode_helper_request_frame,
    decode_result as decode_helper_result,
    decode_result_frame as decode_helper_result_frame,
    encode_request_frame as encode_helper_request_frame,
    encode_result_frame as encode_helper_result_frame,
    read_helper_frame,
    read_request as read_helper_request,
    read_result as read_helper_result,
    encode_request as encode_helper_request,
    encode_result as encode_helper_result,
    write_helper_frame,
    write_request as write_helper_request,
    write_result as write_helper_result,
)

__all__ = [
    "AppServerCodexAdapter",
    "CaptureMemory",
    "CodexRuntime",
    "HardwareAdapter",
    "HardwareCapability",
    "HardwareDispatch",
    "HardwareError",
    "HardwareResult",
    "HardwareResultStatus",
    "HardwareUnavailable",
    "HELPER_PROTOCOL_VERSION",
    "HelperProtocolError",
    "HardwareOperation",
    "InspectRegister",
    "JobHandle",
    "JobRequest",
    "JobStatus",
    "M1N1_QUALIFICATION_MESSAGE",
    "M1n1HardwareAdapter",
    "NoopCodexAdapter",
    "ReplayHardwareAdapter",
    "ReplayMismatch",
    "ReplayStep",
    "RuntimeEvent",
    "RuntimeErrorBase",
    "RuntimeOutcomeUnknown",
    "RuntimeProtocolError",
    "RuntimeRequestNotSent",
    "RuntimeRequestRejected",
    "RuntimeUnavailable",
    "SandboxMode",
    "SimulateBoot",
    "TargetSnapshot",
    "TokenUsage",
    "WaitForReplay",
    "decode_helper_request",
    "decode_helper_request_frame",
    "decode_helper_result",
    "decode_helper_result_frame",
    "encode_helper_request",
    "encode_helper_request_frame",
    "encode_helper_result",
    "encode_helper_result_frame",
    "read_helper_frame",
    "read_helper_request",
    "read_helper_result",
    "write_helper_frame",
    "write_helper_request",
    "write_helper_result",
]
